# This is the development compose file
# Includes MailHog with Web UI, exposes RabbitMQ management UI, uses basic local credentials
services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: usermanagement-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: usermanagement_dev
      POSTGRES_USER: userapp
      POSTGRES_PASSWORD: userapp123
      POSTGRES_ROOT_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U userapp -d usermanagement_dev" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: usermanagement-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI (enabled in dev)
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: usermanagement-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1025" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usermanagement-app
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      # Database configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/usermanagement_dev
      - SPRING_DATASOURCE_USERNAME=userapp
      - SPRING_DATASOURCE_PASSWORD=userapp123
      # Development settings
      - SHOW_SQL=false
      - FORMAT_SQL=false
      - LOG_LEVEL_APP=DEBUG
      - LOG_LEVEL_SQL=WARN
      # Email configuration (development mode)
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - APP_EMAIL_FROM=noreply@usermanagement.com
      - APP_BASE_URL=http://localhost:8082
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - app_logs:/app/logs

volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

networks:
  app-network:
    driver: bridge