spring:
  application:
    name: UserManagement
  datasource:
    url: jdbc:postgresql://localhost:5432/usermanagement_dev
    username: userapp
    password: userapp123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or 'validate'/'none' in prod, 'create-drop' for first-time setup ONLY
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

logging:
  level:
    root: INFO
    me.manulorenzo.usermanagement: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

# Optionally comment/remove H2 console/connection
# h2:
#  console:
#    enabled: false


# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: false
    displayRequestDuration: true
    displayOperationId: false
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: false
  writer-with-default-pretty-printer: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:default-secret-key-change-in-production-and-make-it-longer-than-32-chars}
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutes
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days

# Application-specific configuration
app:
  roles:
    admin: ${APP_ADMIN_ROLE:ADMIN}
    user: ${APP_USER_ROLE:USER}
  security:
    # First user gets admin role automatically
    first-user-admin: ${APP_FIRST_USER_ADMIN:true}
    # Note: Spring Security @PreAuthorize expressions use hardcoded 'ADMIN' role names
    # The database role names above can be different, but security annotations expect 'ADMIN'
