spring:
  application:
    name: UserManagement
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/usermanagement_dev}
    username: ${SPRING_DATASOURCE_USERNAME:userapp}
    password: ${SPRING_DATASOURCE_PASSWORD:userapp123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false  # Disable in Docker for performance
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    me.manulorenzo.usermanagement: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: /app/logs/usermanagement.log
    max-size: 100MB
    max-history: 30

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: false
    displayRequestDuration: true
    displayOperationId: false
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: false
  writer-with-default-pretty-printer: true

# Management endpoints for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:default-secret-key-change-in-production-and-make-it-longer-than-32-chars}
  access-token:
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutes
  refresh-token:
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 days

# Application-specific configuration
app:
  roles:
    admin: ${APP_ADMIN_ROLE:ADMIN}
    user: ${APP_USER_ROLE:USER}
  security:
    # First user gets admin role automatically
    first-user-admin: ${APP_FIRST_USER_ADMIN:true}
    # Note: Spring Security @PreAuthorize expressions use hardcoded 'ADMIN' role names
    # The database role names above can be different, but security annotations expect 'ADMIN'