spring:
  application:
    name: UserManagement
logging:
  level:
    root: INFO
    me.manulorenzo.usermanagement: DEBUG
    pattern:
      console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
